### ISSUE TITLE
Error thrown

### ISSUE THREAD

**Issue by adriantache** [RoJoHub/react-native-ping#22]
Just to make sure, is this intended behaviour? 
```
2019-03-20 15:40:19.331 31167-31197/? W/System.err: java.lang.StringIndexOutOfBoundsException: length=0; index=18
2019-03-20 15:40:19.332 31167-31197/? W/System.err:     at java.lang.String.substring(String.java:1999)
2019-03-20 15:40:19.332 31167-31197/? W/System.err:     at com.reactlibrary.PingUtil.getAvgRTT(Unknown Source:26)
2019-03-20 15:40:19.332 31167-31197/? W/System.err:     at com.reactlibrary.PingUtil.getAvgRTT(Unknown Source:3)
2019-03-20 15:40:19.332 31167-31197/? W/System.err:     at com.reactlibrary.RNReactNativePingModule.start(Unknown Source:17)
2019-03-20 15:40:19.332 31167-31197/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-03-20 15:40:19.332 31167-31197/? W/System.err:     at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:148)
2019-03-20 15:40:19.332 31167-31197/? W/System.err:     at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21)
2019-03-20 15:40:19.332 31167-31197/? W/System.err:     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
2019-03-20 15:40:19.332 31167-31197/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2019-03-20 15:40:19.332 31167-31197/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2019-03-20 15:40:19.332 31167-31197/? W/System.err:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
2019-03-20 15:40:19.332 31167-31197/? W/System.err:     at android.os.Looper.loop(Looper.java:193)
2019-03-20 15:40:19.332 31167-31197/? W/System.err:     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(Unknown Source:16)
2019-03-20 15:40:19.332 31167-31197/? W/System.err:     at java.lang.Thread.run(Thread.java:764)
```

**Comment by RoJoHub** [comment]
![Uploading image.png…]()

**Comment by RoJoHub** [comment]
![image](https://user-images.githubusercontent.com/15648309/54757066-6d6e7580-4c24-11e9-9aec-3ce1183c58ea.png)

**Comment by adriantache** [comment]
Yeah I saw the code and I imagined it's fine since it is in a try/catch block, and I believe it works.

I have just been debugging a stupid problem with my code working on anything but production builds and I was investigating everything since logcat didn't show any errors or anything. Turns out it was unrelated, the app was downloading a different version at launch and of course it didn't have what I wanted in it...

**Comment by RoJoHub** [comment]
> Yeah I saw the code and I imagined it's fine since it is in a try/catch block, and I believe it works.
> 
> I have just been debugging a stupid problem with my code working on anything but production builds and I was investigating everything since logcat didn't show any errors or anything. Turns out it was unrelated, the app was downloading a different version at launch and of course it didn't have what I wanted in it...

Hahahaha. 😄
I really think your avatar looks great. How did you do it?

**Comment by adriantache** [comment]
Haha, thank you. It's nothing special, just something I did in Photoshop years ago. I can make one for you if you want to, just email me.

**Comment by RoJoHub** [comment]
I have sent an email to your email address.
sorry to trouble you.

**Comment by RoJoHub** [comment]
I haven’t thought about what I want for a long time. 
Anyway...........Thank you so much.

**Comment by adriantache** [comment]
Hmm, seems I haven't received your email, I checked spam as well. Just tell me what you want it to say in the middle and I'll make one and post the link here.
